/*
 * This source file was generated by the Gradle 'init' task
 */
package org.UPSkiller;

@SpringBootApplication
@EnableConfigServer
public class App {

    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
    }
}
